import pygame

# загружаем текстуры
menu_button_level = pygame.image.load("images/menunutton1.jpg")
menu_button_editor = pygame.image.load("images/menunutton2.jpg")
play_button = pygame.image.load("images/play_button.jpg")
delete_button = pygame.image.load("images/delete_button.jpg")
left_arrow = pygame.image.load("images/right_arrow.jpg")
right_arrow = pygame.image.load("images/left_arrow.jpg")
temp_bg = pygame.image.load("images/temp_bg.jpg")
grass = pygame.image.load("images/grass.jpg")
castle = pygame.image.load("images/castle.jpg")
spawner = pygame.image.load("images/spawner.jpg")
road = pygame.image.load("images/road.jpg")
cell_menu = pygame.image.load("images/cell_menu.jpg")
save_message = pygame.image.load("images/save_message.jpg")
monster = pygame.image.load("images/monster.png")
tower = pygame.image.load("images/tower.jpg")
game_hud = pygame.image.load("images/game_hud.png")
damaged_monster = pygame.image.load("images/damaged_monster.png")
